version: '3.8'

services:
  # Serviço da Aplicação Spring Boot
  app:
    build: .
    container_name: milhas-api
    ports:
      - "8080:8080"
    environment:
      # Conecta ao banco 'milhas' e define o schema 'milhas'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/milhas?currentSchema=milhas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_SCHEMAS=milhas
    depends_on:
      - db

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: milhas-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=milhas
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Executa o script para criar o schema 'milhas'
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql

volumes:
  postgres-data: