spring.application.name=milhas

spring.datasource.url=jdbc:postgresql://localhost:5432/milhas?currentSchema=milhas
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.flyway.enabled=true
spring.flyway.schemas=milhas
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
server.port=8080

jwt.secret=${JWT_SECRET:bWluaGFfY2hhdmVfc2VjcmV0YV9zdXBlcl9sb25nYV9wYXJhX2dlcmFyX3Rva2Vuc19qd3RfYXV0ZW50aWNhY2Fv}
jwt.expiration=86400000

file.upload-dir=${FILE_UPLOAD_DIR:./uploads}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB