spring.application.name=milhas
server.port=8080

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/milhas?currentSchema=milhas
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.leak-detection-threshold=60000

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# FLYWAY
spring.flyway.enabled=true
spring.flyway.schemas=milhas

# SECURITY (JWT)
<<<<<<< HEAD
jwt.secret=NGRmZjk3YmE2ZGMwYjFlYjU4OGMxYTdkYjE4YjdiM2E0ZWE2YjVkYmU1YmQxZGVmZjVkZTU2Y2Y5YTMxZDY5YQ==
MAILTRAP_TOKEN=98190ad12c408c53c777b12bd8e7913c
=======
jwt.secret={jwt_secret}

>>>>>>> 50fcbfda8feffd931ab49f9efb93b205e9bed941
jwt.expiration=86400000

# STORAGE
file.upload-dir=${FILE_UPLOAD_DIR:./uploads}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# PERFORMANCE & JSON
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/plain,application/javascript,text/css
server.compression.min-response-size=1024
spring.jackson.time-zone=America/Sao_Paulo
spring.mvc.problemdetails.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false

# ACTUATOR
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# LOGGING
logging.level.com.web.milhas=INFO



