INSERT INTO programa_pontos (nome) VALUES ('Livelo') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('Esfera') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('Smiles') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('Latam Pass') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('TudoAzul') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('Átomos') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('Dotz') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('Iupp') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('TAP Miles&Go') ON CONFLICT (nome) DO NOTHING;
INSERT INTO programa_pontos (nome) VALUES ('AAdvantage') ON CONFLICT (nome) DO NOTHING;